### ISSUE TITLE
Installation via composer and symfony compatibility

### ISSUE THREAD

**Issue by sarramegnag** [ambroisemaupate/omnipay-sips#1]
Hi,

Is there any plan about referencing this package on packagist and/or upgrade dependency with omnipay/common to 3.0 and higher versions ?

Regards.

**Comment by ambroisemaupate** [comment]
Hello @sarramegnag 

Unfortunately, I've got no dedicated time to upgrade this project for now.
Feel free to fork or/and create pull request if you want to contribute.

Thanks!

**Comment by sarramegnag** [comment]
No problem !

Thanks for the reply :)
